name: Deploy - Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - "environments/**"
      - "modules/**"
  workflow_dispatch: # permite disparar manualmente desde la pestaña Actions, sin depender de un push que matchee paths

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      nonprod: ${{ steps.filter.outputs.nonprod }}
      prod: ${{ steps.filter.outputs.prod }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            nonprod:
              - 'environments/nonprod/**'
              - 'modules/**'
            prod:
              - 'environments/prod/**'
              - 'modules/**'

  apply-nonprod:
    needs: detect-changes
    if: github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.nonprod == 'true'
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working_directory: environments/nonprod
      environment: nonprod-foundation
    secrets:
      role_arn: ${{ secrets.NONPROD_TERRAFORM_ROLE_ARN }}

  apply-prod:
    needs: detect-changes
    if: github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.prod == 'true'
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working_directory: environments/prod
      environment: prod-foundation
    secrets:
      role_arn: ${{ secrets.PROD_TERRAFORM_ROLE_ARN }}
