name: Terraform Apply (reusable)

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: us-east-1
      environment:
        required: true
        type: string # debe coincidir con un GitHub Environment configurado (con required reviewer en prod)
    secrets:
      role_arn:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} # aquí se aplica el gate de aprobación manual
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Configurar credenciales AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role_arn }}
          aws-region: ${{ inputs.aws_region }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
